### ISSUE TITLE
What languages are supported?

### ISSUE THREAD

**Issue by jurgenhaas** [kuehne-nagel/plantuml-generation-intellij-plugin#2]
I'd like to use this for PHP class diagrams but couldn't get it to work.

Use case: I have an interface and would like to create a diagram with all related classes, including those that implement that interface but also those that get extended by it.

Is that even possible for PHP with this plugin?

**Comment by martinlercara** [comment]
Hello Jürgen,

thank you for your interest in the plugin. It is designed to work with the Java/Kotlin programming language. It does not work with PHP and there are no plans for an extension from our side.

Best regards,
Martin

**Comment by jurgenhaas** [comment]
Hi Martin, thanks for your reply. It's a bit unfortunate, because the PUML export is really what I'm looking for. IntelliJ has the built-in diagram utility, which does a great job in creating the diagram, but it doesn't export them as PUML, unfortunately.

With regard to your plugin, you may want to mention that limitation in the plugin description. That would help others to know better upfront, what it is meant for.
